name: Run Unit Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - master    

jobs:
  test:
    name: Unit Testing
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Tests
      run: dotnet test --logger "console;verbosity=detailed"